[tools]
uv = 'latest'

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.venv]
description = "Set a virtual environment for the project"
# _.python.venv = { path = ".venv", create = true }
run = [
    'uv sync --group dev'
]

[tasks.py-fund-manager]
description = "Run py-fund-manager"
depends = ["venv"]
run = [
    'uv run python -m py_fund_manager'
]

[tasks.build]
description = "Build source and wheel distributions"
run = [
    'uv build'
]

[tasks.clean]
description = "Do local clean-up"
run = [
    'rm -rf .mypy_cache .ruff_cache .venv dist src/py_fund_manager.egg-info',
    'find . -name __pycache__ | xargs rm -rf'
]

[tasks.format]
description = "Format python sources"
run = [
    # sort imports
    'uv run ruff check --select I --fix src/py_fund_manager tests sample-data/strategy/SnP500-direct/generate_strategy.py',
    # reformat sources
    'uv run ruff format -v src/py_fund_manager tests sample-data/strategy/SnP500-direct/generate_strategy.py',
]

[tasks.lint]
description = "Lint python sources"
run = [
    # check imports
    'uv run ruff check -v --select I src/py_fund_manager tests',
    'uv run ruff check -v src/py_fund_manager tests sample-data/strategy/SnP500-direct/generate_strategy.py'
]

[tasks.mypy]
description = "Check typing"
run = [
    'uv run mypy src/py_fund_manager tests sample-data/strategy/SnP500-direct/generate_strategy.py'
]

[tasks.tests]
description = "Execute unit tests"
run = [
    'uv run -m unittest -v tests/*_test.py',
]
